### ISSUE TITLE
Multiple Components

### ISSUE THREAD

**Issue by quangas** [nicoraynaud/react-widget#1]
How would this work if you had multiple components? Let's say you had a second ticker component, how would you setup the App to cater for this?

I can't imagine creating multiple react projects for each component.

**Comment by nicoraynaud** [comment]
Hi,
I think you could use another data html attribute to pass args to the widget and then decide what component to display based on that input.
Something like this maybe ?
```
<div id="something-else-in-your-website">
  <div class="nicoraynaud-finance-widget"
       data-symbol="AMZN" data-component="historical-chart">
  </div>
</div>
```

**Comment by quangas** [comment]
Hi, I meant a new component, so lets say a StockQuoteAdvance component which has more stock information. How would you render this?

Would you in the App.js check the props and render this component with data-component="stock-quote-advance". Is this what you mean?

**Comment by nicoraynaud** [comment]
Yes, exactly, in App.js, you'd check the content of the data attribute and decide what component to render. Everything would share the same codebase, just a if/else displaying one component or the other

**Comment by quangas** [comment]
Ah makes sense 👍
